"""Build a two-class (person, vehicle) YOLO dataset from a YOLO-format BDD100K dump.

Reads an existing YOLO dataset (images, .txt labels and a data.yaml with the
class names, like the Kaggle BDD100K-YOLO mirror), remaps the categories to
person and vehicle by name, splits into train and val, and writes a clean
dataset plus bdd2.yaml. Reading the names from the yaml means it does not care
what order the mirror indexes its classes in.

    python src/prepare_data.py --src kaggle_bdd --out datasets/bdd2

Mapping:
    pedestrian, rider                             -> person
    car, truck, bus, train, motorcycle, bicycle  -> vehicle
    traffic light, traffic sign                   -> dropped
"""
import argparse
import glob
import random
import shutil
from pathlib import Path

PERSON_KEYS = ("pedestrian", "rider", "person", "ped")
VEHICLE_KEYS = ("car", "truck", "bus", "train", "motor", "bicycle", "bike", "vehicle", "van")
CLASSES = ["person", "vehicle"]
CLS_IDX = {c: i for i, c in enumerate(CLASSES)}


def to_class(name):
    n = str(name).lower().strip()
    if any(k in n for k in PERSON_KEYS):
        return "person"
    if any(k in n for k in VEHICLE_KEYS):
        return "vehicle"
    return None


def read_names(src):
    """Find a data.yaml under src and return its class names as an ordered list."""
    import yaml
    for y in sorted(Path(src).rglob("*.yaml")) + sorted(Path(src).rglob("*.yml")):
        try:
            cfg = yaml.safe_load(Path(y).read_text())
        except Exception:
            continue
        names = cfg.get("names") if isinstance(cfg, dict) else None
        if names:
            if isinstance(names, dict):                 # {0: 'car', 1: ...}
                names = [names[k] for k in sorted(names)]
            print(f"class names (from {y}): {names}")
            return list(names)
    raise SystemExit(f"no data.yaml with a 'names:' list found under {src}")


def label_for(img):
    """Locate the YOLO label .txt for an image (…/images/… -> …/labels/…)."""
    p = str(img)
    if "/images/" in p:
        cand = Path(p.replace("/images/", "/labels/")).with_suffix(".txt")
        if cand.exists():
            return cand
    cand = img.with_suffix(".txt")
    return cand if cand.exists() else None


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--src", default="kaggle_bdd", help="root of the YOLO-format dump")
    ap.add_argument("--out", default="datasets/bdd2")
    ap.add_argument("--max-samples", type=int, default=10000, help="0 = all")
    ap.add_argument("--val-frac", type=float, default=0.2)
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()

    names = read_names(args.src)
    remap = {i: to_class(n) for i, n in enumerate(names)}
    print("remap:", {names[i]: remap[i] for i in range(len(names))})

    imgs = [Path(p) for ext in ("jpg", "jpeg", "png", "JPG")
            for p in glob.glob(f"{args.src}/**/*.{ext}", recursive=True)]
    imgs = [p for p in imgs if label_for(p) is not None]
    if not imgs:
        raise SystemExit(f"no images-with-labels found under {args.src}")
    print(f"{len(imgs)} labelled images found")

    random.Random(args.seed).shuffle(imgs)
    if args.max_samples:
        imgs = imgs[: args.max_samples]

    n_val = max(1, int(len(imgs) * args.val_frac))
    out = Path(args.out).resolve()
    for s in ("train", "val"):
        (out / "images" / s).mkdir(parents=True, exist_ok=True)
        (out / "labels" / s).mkdir(parents=True, exist_ok=True)

    kept = {"train": 0, "val": 0}
    box = {"person": 0, "vehicle": 0}
    for i, img in enumerate(imgs):
        s = "val" if i < n_val else "train"
        lines = []
        for ln in Path(label_for(img)).read_text().splitlines():
            parts = ln.split()
            if len(parts) < 5:
                continue
            cls = remap.get(int(float(parts[0])))
            if cls is None:
                continue
            lines.append(f"{CLS_IDX[cls]} " + " ".join(parts[1:5]))
            box[cls] += 1
        stem = f"{i:06d}_{img.stem}"            # unique across subfolders
        shutil.copyfile(img, out / "images" / s / f"{stem}{img.suffix}")
        (out / "labels" / s / f"{stem}.txt").write_text("\n".join(lines))
        kept[s] += 1

    (out / "bdd2.yaml").write_text(
        f"# BDD100K, collapsed to person/vehicle. Generated by src/prepare_data.py\n"
        f"path: {out}\ntrain: images/train\nval: images/val\n"
        f"nc: {len(CLASSES)}\nnames: {CLASSES}\n")

    print(f"\nDone. train={kept['train']} val={kept['val']} "
          f"person_boxes={box['person']} vehicle_boxes={box['vehicle']}")
    print("data config:", out / "bdd2.yaml")


if __name__ == "__main__":
    main()
